### ISSUE TITLE
Blocking script

### ISSUE THREAD

**Issue by pol22pol** [rah606/ns#1]
Nju probably blocked such scripts because the message "Roboty, rzucamy Wam wyzwanie" appears. Is there a workaround for this?

**Comment by mrachuta** [comment]
Hi! Sorry for late response. I never had such issue. Could you please guide me how to reproduce the case?

**Comment by pol22pol** [comment]
Hi, no, I don't have this issue. But I had change you code because I don't have information about 'data okresu rozliczeniowego', I changed to 'dane podstawowe'. Now it works fine.
Nice job! Thx
